### ISSUE TITLE
Add error-handling

### ISSUE THREAD

**Issue by jeffmm** [lamsoa729/KMC#4]
KMC should have an error-handling routine that makes a soft exit from the KMC class and throw an exception, rather than running `exit(1)`, which immediately terminates the process that depends on it. A soft exit would have the advantage of letting people manage their own error logging.

**Comment by lamsoa729** [comment]
Changed from exit(1) to throw. 
Unit tests were made to makes sure that errors are thrown at correct times.
Left std::cerr statements in. Are these necessary with throw statements?

**Comment by jeffmm** [comment]
For warnings, I think it's fine to use std::cerr in debug mode as you are currently doing. For exceptions that precede a throw, I would throw an instance derived from the std::exception class that has some kind of error message built in.
